apiVersion: quay.redhat.com/v1
kind: QuayIntegration
metadata:
  name: quay-registry-integration
spec:
  #allowlistNamespaces:
  #  - gitops-rest
  #  - devsecops-config
  # organizationPrefix: openshift
  credentialsSecret:
    name: quay-integration-secret
    namespace: openshift-operators
    key: token
  clusterID: openshift
  insecureRegistry: false
  quayHostname: <QUAY_ROUTE>