apiVersion: quay.redhat.com/v1
kind: QuayIntegration
metadata:
  name: quay-registry-integration
spec:
  #allowlistNamespaces:
  #  - nodejs-gitops-pipeline
  #  - devsecops-config
  #  - openshift
  # organizationPrefix: openshift
  credentialsSecret:
    name: quay-integration-secret
    namespace: openshift-operators
    key: token
  clusterID: openshift
  insecureRegistry: false
  quayHostname: https://quay-registry-quay-openshift-operators.apps.cluster-k6qgg.k6qgg.sandbox1473.opentlc.com