schemaVersion: 2.1.0
metadata:
  name: skunkworks
components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.5
      memoryLimit: 2Gi
      mountSources: true

#commands:
#  - id: run-main-script
#    exec:
#      label: "Run main.sh script"
#      component: tools
#      workingDir: '${PROJECT_SOURCE}'
#      commandLine: |
#        ./main.sh
#      group:
#        kind: run
#        isDefault: true