apiVersion: v1
kind: List
items:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: golang-base
      labels:
        app-owner: openshift-skunkworks
        app.openshift.io/runtime: golang
    spec:
      source:
        git:
          ref: main
          uri: "https://github.com/redhat-partner-ecosystem/openshift-skunkworks"
        contextDir: images/golang_s2i
        type: Git
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: golang-base:1.18
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange

  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: golang-base
      labels:
        app-owner: openshift-skunkworks
        app.openshift.io/runtime: golang
      annotations:
        description: golang-base s2i builder base image
